logicalclocks/hops-examples

flink/pom.xml

to avoid Invalid signature file digest for Manifest main attributes error

corrections to the flink example

---

notebooks/spark/PySparkWithHive.ipynb

Have been tested on a VM built with this config: https://github.com/logicalclocks/hops-testing/pull/223

[HOPSWORKS-745]: Add sparkOnHive example notebook

---

notebooks/featurestore/FeaturestoreTourPython.ipynb
notebooks/featurestore/FeaturestoreTourScala.ipynb

- Update example notebooks and jobs to use jobName:
This should be merged only after these PRs are merged:
https://github.com/logicalclocks/hops-util-py/pull/27
https://github.com/logicalclocks/hops-util/pull/23

[HOPSWORKS-866] Change jobId to JobName in feature store API

---

notebooks/featurestore/FeatureStoreQuickStart.ipynb
notebooks/featurestore/FeaturestoreTourPython.ipynb

- Fix syntax error in python notebook

[Hopsworks 906] - Bugfix

---

notebooks/featurestore/FeaturestoreTourPython.ipynb
notebooks/featurestore/FeaturestoreTourScala.ipynb

- Clarify cache-semantics in the FS-tour

[HOPSWORKS-911] Cache featurestore metadata on client

---

notebooks/featurestore/petastorm/PetastormMNIST_CreateDataset.ipynb

[HOPSWORKS-852] (append) add petastorm support

---

notebooks/featurestore/FeaturestoreTourPython.ipynb
notebooks/featurestore/FeaturestoreTourScala.ipynb

- Update tour example to show how to specify hive partitions of feature groups

[HOPSWORKS-1025] add Hive Partitioning support for feature groups

---

tensorflow/notebooks/Serving/tensorflow/serving_client.ipynb
tensorflow/notebooks/Serving/tensorflow/train_and_export_model.ipynb

- use new REST API for servings

[HOPSWORKS-1123] Update Tensorflow Serving Examples

---

tensorflow/notebooks/Parallel_Experiments/Maggy/maggy-fashion-mnist-example.ipynb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1179

[HOPSWORKS-1179] Add Maggy MNIST example notebook to DL tour

---

featurestore_util/featurestore_util_py/featurestore_util.py

- add extra preprocessing to featurestore-util-py

[HOPSWORKS-1196][featurestore] append

---

featurestore_tour/src/main/scala/io/hops/examples/featurestore_tour/featuregroups/ComputeFeatures.scala
featurestore_util/featurestore_util4j/src/main/scala/io/hops/examples/featurestore_util4j/Main.scala
notebooks/featurestore/online_featurestore/OnlineFeaturestoreTourPython.ipynb
notebooks/featurestore/online_featurestore/OnlineFeaturestoreTourScala.ipynb

- online feature store examples

[HOPSWORKS-1139][Umbrella] Online Feature Store

---

notebooks/featurestore/datasets/TitanicTrainingDatasetPython.ipynb

This PR adds a notebook that can be used to create a training dataset for the Titanic dataset on the feature store.

[HOPSWORKS-1348] Adds notebook for Titanic training dataset on the feature store 

---

featurestore_tour/src/main/scala/io/hops/examples/featurestore_tour/featuregroups/ComputeFeatures.scala
notebooks/featurestore/FeaturestoreTourScala.ipynb
notebooks/featurestore/hudi/HudiOnHops.ipynb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1378
Updated the notebooks. Merge instead of #95 
We decided to keep the API the same with `primaryKey` instead of changing it to `primaryKeys`.

[HOPSWORKS-1378][featurestore][append] composite key DDL support

---

notebooks/ml/Experiment/PyTorch/mnist.ipynb
notebooks/ml/Parallel_Experiments/PyTorch/differential_evolution/mnist.ipynb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1418

[HOPSWORKS-1418] upgrade pytorch and examples to 1.3.1 and add a tensorboard example

---

notebooks/spark/Elasticsearch-python.ipynb
notebooks/spark/Elasticsearch-scala.ipynb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1476
tests: https://github.com/logicalclocks/hops-testing/pull/567

[HOPSWORKS-1476] Add support for elasticsearch spark connector

---

notebooks/ml/Parallel_Experiments/Maggy/maggy-fashion-mnist-example.ipynb

https://logicalclocks.atlassian.net/browse/HOPSWORKS-1635

[HOPSWORKS-1635] Update Maggy Fashion MNIST for TF1.15

---

notebooks/ml/Parallel_Experiments/Maggy/maggy-ablation-titanic-example.ipynb

Synchronizes the example notebook with the latest on Maggy's repo.

[HOPSWORKS-1757] Update Maggy ablation example notebook with fix for TF pickling issue

---

notebooks/ml/End_To_End_Pipeline/tensorflow/model_repo_and_serving.ipynb
notebooks/ml/Parallel_Experiments/TensorFlow/evolutionary_search/evolutionary_search_mnist.ipynb
notebooks/ml/Parallel_Experiments/TensorFlow/grid_search/grid_search_fashion_mnist.ipynb

"[HOPSWORKS-1642] Append, set correct path for training dataset in Parallel_Experiments" 
[HOPSWORKS-1642]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-1642

"HOPSWORKS-1642 Append, set correct path for training dataset in Parallel_Experiments"

---

notebooks/featurestore/FeaturestoreTourScala.ipynb

Spark-TFRecord works. However, there are some issues with on demand features and petastorm

[HOPSWORKS-1762] Add support for Spark-Tfrecord

---

featurestore_tour/src/main/scala/io/hops/examples/featurestore_tour/featuregroups/ComputeFeatures.scala

Fix hudi compatibility. For now I set everything to NONE, which means disabled hudi time travel format

[HOPSWORKS-1374] Add Hudi API to HSFS and commits to the FeatureStore

---

notebooks/ml/Parallel_Experiments/Maggy/maggy-pytorch-example.ipynb

Added PyTorch Maggy example notebook.

[HOPSWORKS-2342] Add PyTorch Maggy hyperparameter optimization example notebook

---

notebooks/featurestore/aws/redshift/Redshift_spark.ipynb
notebooks/featurestore/hsfs/snowflake/scala.ipynb

https://github.com/logicalclocks/feature-store-api/pull/313

Subclass the different storage connector types

---

notebooks/featurestore/hsfs/online_transformations/online_transformations.ipynb

Reverts logicalclocks/hops-examples#224

Revert "[HOPSWORKS-2424][APPEND] Attach transformation function to training dataset"

---

notebooks/ml/Benchmarks/benchmark.ipynb

Fix path to Experiments.gif in benchmark notebook.

Fix path to Experiments.gif

---

Jenkinsfile_examples

use single quote so that Groovy is not interpolating the variable

[HOPSWORKS-2867][APPEND] single quote - interpolation

---

themes/berbera/layouts/partials/head-meta.html

Add favicon to https://examples.hopsworks.ai/

Add favicon to https://examples.hopsworks.ai/

---

themes/berbera/layouts/_default/baseof.html
themes/berbera/layouts/partials/head-meta.html

favicon update for examples.hopsworks.ai/

favicon update

---

notebooks/featurestore/hsfs/online_featurestore/1_create_feature_groups.ipynb
notebooks/featurestore/hsfs/online_featurestore/3_stream-ingestion.ipynb
notebooks/featurestore/hsfs/online_featurestore/4_create_training_dataset.ipynb

With new 0.10.0 hudi I need set `hoodie.datasource.write.insert.drop.duplicates` to `false`. Also delta streamer needs to triggered manually

[HOPSWORKS-2543] add support to insert_stream() to ingest data into offline fs
